language: ruby
cache: bundler
addons:
  postgresql: '9.4'
env:
- TEST_DATABASE_URL=postgres://localhost/travis_ci_test
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bin/rake db:migrate
- bin/rake ci:all
sudo: false